### PR TITLE
Feature/aut 22/add ckeditor to inline choice

### PR DESCRIPTION
**Pull request by AnastasiaArcadia**
**Related to:** https://oat-sa.atlassian.net/browse/AUT-22

**How to test**
- Create inline choice interaction
- Try to add different markup and math to the choices
- Add new / delete choices
- Save item

**Related PR:** https://github.com/oat-sa/extension-tao-itemqti/pull/1797

Env: http://test-anastasia.playground.kitchen.it.taocloud.org:44451/

### CODE REVIEW

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
lgtm

**Comment by mike-ionut-mihai-sandu-tao** [comment]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Review by bziondik — CHANGES_REQUESTED** [review]

**Review by Silvia-loza — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

**Review by bziondik — CHANGES_REQUESTED** [review]
Check unit tests
image

**Review by bziondik — APPROVED** [review]
**Please change `develop` to integration branch!**
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Pull request merged**
