### PR TITLE
Added additional logger for checking requiredClasses

### PR DESCRIPTION
**Pull request by tikhanovichA**
https://oat-sa.atlassian.net/browse/NCSUP-257

For fixing the issue we need to add one more level of log messages with full information about QTI classes.

**p.s. Do we need to add these changes in to develop branch, or we can just create a backport for one specific version?**

### CODE REVIEW

**Comment by krampstudio** [comment]
@tikhanovichA you have solutions  : 
1. deploy that as a backport and not merge it into develop
2. either add the required informations in the log record (you can give an object in argument, that should be transmitted)

**Comment by tikhanovichA** [comment]
@krampstudio Thanks a lot for your response. 
[1] Yes, I will delete that PR and will create just the backport.
[2] If I will add all that info into Error object, then a final user will see a huge red block with a lot of information. I think it will be not very user-friendly.

**Comment by krampstudio** [comment]
> [2] If I will add all that info into Error object, then a final user will see a huge red block with a lot of information. I think it will be not very user-friendly.
I meant, the logger supports directly adding contextual informations
```js
logger.error({ requiredClasses, data}, 'Something went wrong')
```

**Comment by tikhanovichA** [comment]
Thanks, @krampstudio . Will do it asap

**Comment by tikhanovichA** [comment]
New backport PR was created 
https://github.com/oat-sa/tao-item-runner-qti-fe/pull/40

**Pull request closed without merging**
